### ISSUE TITLE
errors about building and runCIFAR.sh

### ISSUE THREAD

**Issue by dahaichangge** [deepspark/deepspark#2]
After "mvn package",i opened "runCIFAR.sh",and i found that "cifar10_deepspark.prototxt" did not exist. Is there any errors about  "runCIFAR.sh"? I created a fake "cifar10_deepspark.prototxt"  ,then run the runCIFAR.sh,and it is wrong：

16/06/30 19:55:27 INFO cluster.YarnClientSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.8
Exception in thread "main" com.google.protobuf.TextFormat$ParseException: 1:1: Message type "DeepSparkParam" has no field named "name".
        at com.google.protobuf.TextFormat$Tokenizer.parseExceptionPreviousToken(TextFormat.java:923)
        at com.google.protobuf.TextFormat.mergeField(TextFormat.java:1125)
        at com.google.protobuf.TextFormat.merge(TextFormat.java:1062)
        at com.google.protobuf.TextFormat.merge(TextFormat.java:1028)
        at com.google.protobuf.TextFormat.merge(TextFormat.java:998)
        at org.acl.deepspark.utils.DeepSparkParamLoader.readConf(DeepSparkParamLoader.java:14)
        at org.acl.deepspark.nn.driver.AsyncEASGDCIFARLocalTest.main(AsyncEASGDCIFARLocalTest.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16/06/30 19:55:27 INFO spark.SparkContext: Invoking stop() from shutdown hook
16/06/30 19:55:27 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/metrics/json,null}

Any help would be greatly appreciated!
Many thanks in advance.

**Comment by y-c-chiu** [comment]
I have the same problem.
How was it resolved?
Thanks.
